initial change by tei952

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -54,6 +54,50 @@ volumes:
     driver: ${VOLUMES_DRIVER}
   react:
     driver: ${VOLUMES_DRIVER}
+  saleor-db:
+    driver: ${VOLUMES_DRIVER}
+  saleor-redis:
+    driver: ${VOLUMES_DRIVER}
+  saleor-media:
+  nexus-data: {}
+x-airflow-common:
+  &airflow-common
+  # In order to add custom dependencies or upgrade provider packages you can use your extended image.
+  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
+  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
+  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.2.3}
+  # build: .
+  environment:
+    &airflow-common-env
+    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
+    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
+    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
+    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
+    AIRFLOW__CORE__FERNET_KEY: ''
+    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
+    AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
+    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
+    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
+  volumes:
+    - ./dags:/opt/airflow/dags
+    - ./logs:/opt/airflow/logs
+    - ./plugins:/opt/airflow/plugins
+    - /home/tei952/data:/home/tei952/horserace/data
+    - /home/tei952/temp:/home/tei952/horserace/temp
+    - /home/tei952/src/dotnet:/home/tei952/horserace/src/dotnet
+    - /home/tei952/src/python:/home/tei952/horserace/src/python
+  user: "${AIRFLOW_UID:-50000}:0"
+  depends_on:
+    &airflow-common-depends-on
+    redis:
+      condition: service_healthy
+    postgres:
+      condition: service_healthy
+    mssql:
+      condition: service_healthy
+    mysql:
+      condition: service_healthy
+
 
 services:
 
@@ -597,6 +641,7 @@ services:
       volumes:
         - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
         - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
+        - ./saleor-platform/replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
       ports:
         - "${POSTGRES_PORT}:5432"
       environment:
@@ -615,10 +660,14 @@ services:
         - SONARQUBE_POSTGRES_DB=${SONARQUBE_POSTGRES_DB}
         - SONARQUBE_POSTGRES_USER=${SONARQUBE_POSTGRES_USER}
         - SONARQUBE_POSTGRES_PASSWORD=${SONARQUBE_POSTGRES_PASSWORD}
-        - POSTGRES_CONFLUENCE_INIT=${CONFLUENCE_POSTGRES_INIT}
-        - POSTGRES_CONFLUENCE_DB=${CONFLUENCE_POSTGRES_DB}
-        - POSTGRES_CONFLUENCE_USER=${CONFLUENCE_POSTGRES_USER}
-        - POSTGRES_CONFLUENCE_PASSWORD=${CONFLUENCE_POSTGRES_PASSWORD}
+        - CONFLUENCE_POSTGRES_INIT=${CONFLUENCE_POSTGRES_INIT}
+        - CONFLUENCE_POSTGRES_DB=${CONFLUENCE_POSTGRES_DB}
+        - CONFLUENCE_POSTGRES_USER=${CONFLUENCE_POSTGRES_USER}
+        - CONFLUENCE_POSTGRES_PASSWORD=${CONFLUENCE_POSTGRES_PASSWORD}
+        - SALOR_POSTGRES_INIT=${SALOR_POSTGRES_INIT}
+        - SALOR_POSTGRES_DB=${SALOR_POSTGRES_DB}
+        - SALOR_POSTGRES_USER=${SALOR_POSTGRES_USER}
+        - SALOR_POSTGRES_PASSWORD=${SALOR_POSTGRES_PASSWORD}
       networks:
         - backend
 
@@ -1426,10 +1475,11 @@ services:
           nginx['listen_https'] = false
           nginx['listen_port'] = 80
           nginx['custom_gitlab_server_config'] = "set_real_ip_from 172.0.0.0/8;\nreal_ip_header X-Real-IP;\nreal_ip_recursive on;"
-          postgresql['enable'] = false
+          postgresql['enable'] = true
           gitlab_rails['trusted_proxies'] = ['caddy','nginx','apache2']
           gitlab_rails['redis_host'] = 'redis'
           gitlab_rails['redis_database'] = 8
+          gitlab_rails['redis_password'] = '${REDIS_PASSWORD}'
           gitlab_rails['db_host'] = '${GITLAB_POSTGRES_HOST}'
           gitlab_rails['db_username'] = '${GITLAB_POSTGRES_USER}'
           gitlab_rails['db_password'] = '${GITLAB_POSTGRES_PASSWORD}'
@@ -2058,3 +2108,306 @@ services:
         - ${TARANTOOL_ADMIN_PORT}:80
       networks:
         - backend
+
+### salor_api ###########################################
+    salor_api:
+      ports:
+        - ${SALOR_API_PORT}:8000
+      build:
+        context: ./saleor-platform/saleor
+        dockerfile: ./Dockerfile
+        args:
+          STATIC_URL: "/static/"
+      restart: unless-stopped
+      networks:
+        - backend
+      depends_on:
+        - postgres
+        - redis
+        - jaeger
+      volumes:
+        - ./saleor-platform/saleor/saleor/:/app/saleor:Z
+        - ./saleor-platform/saleor/templates/:/app/templates:Z
+        - ./saleor-platform/saleor/tests/:/app/tests
+        # shared volume between worker and api for media
+        - saleor-media:/app/media
+      command: python manage.py runserver 0.0.0.0:${SALOR_API_PORT}
+      env_file:
+        - ./saleor-platform/common.env
+        - ./saleor-platform/backend.env
+      environment:
+        - JAEGER_AGENT_HOST=jaeger
+        - STOREFRONT_URL=http://localhost:${REACT_STOREFRONT_PORT}/
+        - DASHBOARD_URL=http://localhost:${SALOR_DASHBOARD_PORT}/
+        - ALLOWED_HOSTS=localhost,api
+
+### react-storefront ###########################################
+    react-storefront:
+      build:
+        context: ./saleor-platform/react-storefront
+        dockerfile: ./Dockerfile.dev
+      ports:
+        - ${REACT_STOREFRONT_PORT}:3001
+      restart: unless-stopped
+      networks:
+        - backend
+      depends_on:
+        - salor_api
+      volumes:
+        - ./saleor-platform/react-storefront/:/app:cached
+        - /app/node_modules/
+      # Nginx is used to proxy SSR requests thru docker networking
+      command: sh -c '(nginx &) && pnpm dev'
+      environment:
+        - NEXT_PUBLIC_API_URI=http://localhost:${SALOR_API_PORT}/graphql/
+        - NEXT_PUBLIC_HOMEPAGE_MENU=navbar
+
+### salor_dashboard ###########################################
+    salor_dashboard:
+      build:
+        context: ./saleor-platform/saleor-dashboard
+        dockerfile: ./Dockerfile.dev
+      ports:
+        - ${SALOR_DASHBOARD_PORT}:9000
+      restart: unless-stopped
+      volumes:
+        - ./saleor-platform/saleor-dashboard/:/app:cached
+        - /app/node_modules/
+      command: npm start -- --host 0.0.0.0
+
+### salor_worker ###########################################
+    salor_worker:
+      build:
+        context: ./saleor-platform/saleor
+        dockerfile: ./Dockerfile
+        args:
+          STATIC_URL: "/static/"
+      command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
+      restart: unless-stopped
+      networks:
+        - backend
+      env_file:
+        - ./saleor-platform/common.env
+        - ./saleor-platform/backend.env
+      depends_on:
+        - redis
+        - mailhog
+      volumes:
+        - ./saleor-platform/saleor/saleor/:/app/saleor:Z,cached
+        - ./saleor-platform/saleor/templates/:/app/templates:Z,cached
+        # shared volume between worker and api for media
+        - saleor-media:/app/media
+
+### jaeger ###########################################
+    jaeger:
+      image: jaegertracing/all-in-one
+      ports:
+        - "5775:5775/udp"
+        - "6831:6831/udp"
+        - "6832:6832/udp"
+        - "5778:5778"
+        - "16686:16686"
+        - "14268:14268"
+        - "9411:9411"
+      restart: unless-stopped
+      networks:
+        - backend
+
+### optuna ###########################################
+    optuna:
+      image: tei952/optuna_image:0.0.2
+      working_dir: "/workspace"
+      ports:
+        - "6006:6006"
+        - "8888:8888"
+      #runtime: nvidia
+      volumes:
+        - /home/tei952/horserace/data:/home/tei952/horserace/data
+        - /home/tei952/horserace/src/python:/home/tei952/horserace/src/python
+      tty: true
+
+### airflow-webserver ###########################################
+    airflow-webserver:
+      <<: *airflow-common
+      command: webserver
+      ports:
+        - 8080:8080
+      healthcheck:
+        test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
+        interval: 10s
+        timeout: 10s
+        retries: 5
+      restart: always
+      depends_on:
+        <<: *airflow-common-depends-on
+        airflow-init:
+          condition: service_completed_successfully
+
+### airflow-scheduler ###########################################
+    airflow-scheduler:
+      <<: *airflow-common
+      command: scheduler
+      healthcheck:
+        test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
+        interval: 10s
+        timeout: 10s
+        retries: 5
+      restart: always
+      depends_on:
+        <<: *airflow-common-depends-on
+        airflow-init:
+          condition: service_completed_successfully
+
+### airflow-worker ###########################################
+    airflow-worker:
+      <<: *airflow-common
+      command: celery worker
+      healthcheck:
+        test:
+          - "CMD-SHELL"
+          - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
+        interval: 10s
+        timeout: 10s
+        retries: 5
+      environment:
+        <<: *airflow-common-env
+        # Required to handle warm shutdown of the celery workers properly
+        # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
+        DUMB_INIT_SETSID: "0"
+      restart: always
+      depends_on:
+        <<: *airflow-common-depends-on
+        airflow-init:
+          condition: service_completed_successfully
+
+### airflow-triggerer ###########################################
+    airflow-triggerer:
+      <<: *airflow-common
+      command: triggerer
+      healthcheck:
+        test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
+        interval: 10s
+        timeout: 10s
+        retries: 5
+      restart: always
+      depends_on:
+        <<: *airflow-common-depends-on
+        airflow-init:
+          condition: service_completed_successfully
+
+### airflow-init ###########################################
+    airflow-init:
+      <<: *airflow-common
+      entrypoint: /bin/bash
+      # yamllint disable rule:line-length
+      command:
+        - -c
+        - |
+          function ver() {
+            printf "%04d%04d%04d%04d" $${1//./ }
+          }
+          airflow_version=$$(gosu airflow airflow version)
+          airflow_version_comparable=$$(ver $${airflow_version})
+          min_airflow_version=2.2.0
+          min_airflow_version_comparable=$$(ver $${min_airflow_version})
+          if (( airflow_version_comparable < min_airflow_version_comparable )); then
+            echo
+            echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
+            echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
+            echo
+            exit 1
+          fi
+          if [[ -z "${AIRFLOW_UID}" ]]; then
+            echo
+            echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
+            echo "If you are on Linux, you SHOULD follow the instructions below to set "
+            echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
+            echo "For other operating systems you can get rid of the warning with manually created .env file:"
+            echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#setting-the-right-airflow-user"
+            echo
+          fi
+          one_meg=1048576
+          mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
+          cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
+          disk_available=$$(df / | tail -1 | awk '{print $$4}')
+          warning_resources="false"
+          if (( mem_available < 4000 )) ; then
+            echo
+            echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
+            echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
+            echo
+            warning_resources="true"
+          fi
+          if (( cpus_available < 2 )); then
+            echo
+            echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
+            echo "At least 2 CPUs recommended. You have $${cpus_available}"
+            echo
+            warning_resources="true"
+          fi
+          if (( disk_available < one_meg * 10 )); then
+            echo
+            echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
+            echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
+            echo
+            warning_resources="true"
+          fi
+          if [[ $${warning_resources} == "true" ]]; then
+            echo
+            echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
+            echo "Please follow the instructions to increase amount of resources available:"
+            echo "   https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#before-you-begin"
+            echo
+          fi
+          mkdir -p /sources/logs /sources/dags /sources/plugins
+          chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
+          exec /entrypoint airflow version
+      # yamllint enable rule:line-length
+      environment:
+        <<: *airflow-common-env
+        _AIRFLOW_DB_UPGRADE: 'true'
+        _AIRFLOW_WWW_USER_CREATE: 'true'
+        _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
+        _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
+      user: "0:0"
+      volumes:
+        - .:/sources
+
+### airflow-cli ###########################################
+    airflow-cli:
+      <<: *airflow-common
+      profiles:
+        - debug
+      environment:
+        <<: *airflow-common-env
+        CONNECTION_CHECK_MAX_COUNT: "0"
+      # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
+      command:
+        - bash
+        - -c
+        - airflow
+
+### flower ###########################################
+    flower:
+      <<: *airflow-common
+      command: celery flower
+      ports:
+        - 5555:5555
+      healthcheck:
+        test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
+        interval: 10s
+        timeout: 10s
+        retries: 5
+      restart: always
+      depends_on:
+        <<: *airflow-common-depends-on
+        airflow-init:
+          condition: service_completed_successfully
+### nexus ###########################################
+    nexus:
+      image: sonatype/nexus
+      volumes:
+        - "nexus-data:/sonatype-work"
+      ports:
+        - 8081:8081
+  
